<?php

namespace AppBundle\Repository;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFreeInstance()
    {
        return $this->createQueryBuilder('i')
            ->where('i.isFull = 0')
            ->getQuery()
            ->getFirstResult();
    }
}
