<?php

namespace AppBundle\Repository;

/**
 * TypeNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
